(()=>{
      const GLASS_COLORS=[
        {id:'white',name:'White / Clear',hex:'#EAE6DA',rarity:1,sources:['Bottles','Jars','Tableware','Window glass'],refs:['Beachcombing Magazine','Rock & Gem','Visit Southwest Michigan'],note:'Clear glass can come from bottles, jars, tableware, windows, and industrial glass. Lake Michigan sources consistently describe white or clear as one of the most familiar finds.'},
        {id:'brown',name:'Brown / Amber',hex:'#7b563c',rarity:1,sources:['Beer & root-beer bottles','Medicine & bitters bottles','Household-product bottles'],refs:['Beachcombing Magazine','Rock & Gem','Schlitz Audubon'],note:'Brown and amber glass commonly came from beverage, medicine, bitters, and household-product bottles; darker glass also helped protect contents from light.'},
        {id:'aqua',name:'Light Aqua',hex:'#8cc9c5',rarity:2,sources:['Canning jars','Ink bottles','Medicine bottles'],refs:['Beachcombing Magazine','Schlitz Audubon','Visit Southwest Michigan'],note:'Light aqua is strongly associated with utility glass such as canning jars, ink bottles, and medicine bottles. Around Lake Michigan it is a familiar historic bottle color.'},
        {id:'seafoam',name:'Sea Foam',hex:'#a9d4ca',rarity:2,sources:['Bottles','Canning jars','Ink bottles'],refs:['Beachcombing Magazine'],note:'Sea-foam blue-green can result from iron in the sand used to make glass and also appears in intentionally colored bottles, canning jars, and ink bottles.'},
        {id:'green',name:'Kelly / Emerald Green',hex:'#5d8f72',rarity:3,sources:['Beer bottles','Juice & soda bottles','Wine bottles'],refs:['Beachcombing Magazine','Rock & Gem','Visit Southwest Michigan'],note:'Green glass appears in many shades and commonly came from beverage bottles, especially beer, juice, soda, and wine.'},
        {id:'olive',name:'Olive Green',hex:'#7f8558',rarity:4,sources:['Wine bottles','Medicine bottles','Utility containers'],refs:['Schlitz Audubon','Beachcombing Magazine'],note:'Olive sits within the broad historic green-bottle family. Milwaukee sources specifically describe olive as locally produced but somewhat less common than the most familiar shades.'},
        {id:'lime',name:'Lime Green',hex:'#a6ba5f',rarity:6,sources:['20th-century soda bottles','Beer bottles','Medicine bottles','Depression glass'],refs:['Beachcombing Magazine'],note:'Bright lime green appears in 20th-century soda and beer bottles and also in medicinal, art, and Depression glass.'},
        {id:'cobalt',name:'Cobalt / Dark Blue',hex:'#557ab6',rarity:5,sources:['Medicine & poison bottles','Ink & perfume bottles','Specialty bottles'],refs:['Beachcombing Magazine','Schlitz Audubon'],note:'Blue glass was widely used for medicine and specialty containers, as well as ink, perfume, decorative glass, and some beverage bottles. Cobalt was also manufactured in Milwaukee.'},
        {id:'darkaqua',name:'Dark Aqua',hex:'#4f9297',rarity:5,sources:['Seltzer bottles','Electrical insulators','Tableware & art glass'],refs:['Beachcombing Magazine'],note:'Darker aqua can point toward seltzer bottles, early electrical insulators, fancy tableware, art glass, or stained glass.'},
        {id:'teal',name:'Teal / Turquoise',hex:'#4f9c97',rarity:7,sources:['Utility bottles & jars','Ink & wine bottles','Electrical insulators','Depression glass'],refs:['Beachcombing Magazine'],note:'Teal was not only decorative: it was used extensively for utilitarian bottles and jars, along with ink bottles, wine bottles, insulators, and Depression glass.'},
        {id:'milkglass',name:'Milk Glass',hex:'#f1eee5',rarity:4,sources:['Perfume & cosmetic jars','Ointment containers','Opaque household glass'],refs:['Schlitz Audubon','Beachcombing Magazine'],note:'Milk glass is opaque rather than simply frosted. Regional sources associate white milk glass with perfume, ointment, cosmetic, and household containers.'},
        {id:'lavender',name:'Lavender / Amethyst',hex:'#cdb8d3',rarity:7,sources:['Sun-altered clear glass','Flasks & decanters','Bitters bottles','Decorative glass'],refs:['Society for Historical Archaeology — Historic Glass Bottle Identification','Beachcombing Magazine'],note:'A pale or uneven lavender/amethyst cast can indicate originally colorless glass made with manganese as a decolorizer and later solarized by ultraviolet exposure. For U.S. container glass, ca. 1890–1920 is a strong probable range, with some examples extending into the 1930s. Deep, even purple can instead be intentionally colored and should not receive the manganese date automatically.'},
        {id:'pink',name:'Pink',hex:'#e2b6bd',rarity:8,sources:['20th-century housewares','Decorative tableware','Sun-altered clear glass'],refs:['Beachcombing Magazine'],note:'Pink often traces to decorative plates, glasses, and housewares, although manganese in formerly clear glass can also produce peachy tones after long sun exposure.'},
        {id:'purple',name:'Deep Purple',hex:'#7d5b83',rarity:8,sources:['Decorative glassware','Flasks & decanters','Bitters bottles'],refs:['Beachcombing Magazine'],note:'Deep purple is more likely to suggest specialty or decorative glass than an everyday bottle, though dark amethyst can overlap with manganese-altered glass.'},
        {id:'gray',name:'Gray',hex:'#9da4a3',rarity:8,sources:['Leaded tableware','Cut glass','Decorative glass','Glass tiles'],refs:['Beachcombing Magazine'],note:'Gray pieces may come from formerly clear leaded or cut glass whose appearance changed with long exposure, or from discarded tiles and other specialty glass.'},
        {id:'yellow',name:'Yellow',hex:'#e0c86d',rarity:9,sources:['Art & stained glass','Fine tableware','Jars','Signal lights'],refs:['Beachcombing Magazine'],note:'Yellow appears in art glass, stained glass, fine tableware, jars, and signal lights. Some pale yellow glass began clear and shifted color because of selenium.'},
        {id:'opalescent',name:'Opalescent',hex:'#d8ddd2',rarity:9,sources:['Decorative glassware','Early opal glass'],refs:['Beachcombing Magazine'],note:'Opalescent glass is translucent and can show warm orange along thin edges. It was used especially in decorative glassware in the early 20th century.'},
        {id:'canary',name:'Canary / Vaseline',hex:'#d6df63',rarity:10,sources:['Tableware','Household items'],refs:['Beachcombing Magazine'],note:'Canary or Vaseline glass is yellow-green and was used mainly for tableware and household pieces. Historic examples often contain uranium and can fluoresce vivid green under ultraviolet light.'},
        {id:'black',name:'Black / Near-Opaque',hex:'#333333',rarity:8,sources:['Deeply colored bottles','Dark specialty glass'],refs:['Beachcombing Magazine'],note:'Most glass that looks black is actually very dark green, brown, red, blue, or purple. Strong backlighting can reveal the underlying color.'},
        {id:'red',name:'Red',hex:'#c65c4d',rarity:10,sources:['Decorative glass','Perfume bottles','Vehicle & nautical signal lights','Tableware'],refs:['Beachcombing Magazine','Rock & Gem','Visit Southwest Michigan'],note:'Red is a standout Lake Michigan find. It can come from decorative glass, perfume bottles, tableware, and signal lights, and regional sources consistently describe it as rare.'},
        {id:'orange',name:'Orange',hex:'#da8b57',rarity:10,sources:['Art glass','Decorative glass','Reflectors & signal lights','Carnival glass'],refs:['Beachcombing Magazine','Rock & Gem','Visit Southwest Michigan'],note:'Orange glass was not produced in large quantities and most often traces to decorative or art glass, reflectors, signal lights, or Carnival glass.'},
        {id:'slag',name:'Industrial Slag',hex:'#75898b',rarity:6,sources:['Iron-smelting byproduct','Leland Blue','Frankfort Green'],refs:['Beachcombing Magazine','Rock & Gem'],note:'Industrial slag is not ordinary bottle glass. Leland Blue and Frankfort Green are Great Lakes smelting byproducts; decorative marbled “slag glass” is a different manufactured glass category.'}
      ];
      const REGIONS={
        chicago:{label:'Chicago',refs:['Beachcombing Magazine — Urban Beachcombing'],blurb:"Chicago's lakefront contains extensive historic fill, and local beachcombing reports include finds associated with the Great Chicago Fire and Chicago's World's Fairs. That history is useful context, but a shoreline find cannot be assigned to one event from location alone.",colorNote:{white:"Plain white or clear pieces can overlap with ordinary bottle glass, tableware, and construction glass.",lavender:"Lavender glass can be especially interesting because manganese-containing clear glass may shift toward violet after long sunlight exposure.",slag:"Industrial slag is more strongly documented along parts of the Michigan shoreline than directly in Chicago."}},
        milwaukee:{label:'Milwaukee',refs:['Schlitz Audubon Nature Center'],blurb:"Milwaukee has unusually useful industrial context: glass entered the lake through historic dumping, a railroad dump north of the city eroded toward the shoreline, and Chase Valley Glass Company began local production in 1880.",colorNote:{cobalt:"Cobalt glass was manufactured in the Milwaukee area, so a local cobalt find has a plausible regional production context.",red:"A Milwaukee-area collector interviewed by Schlitz Audubon reported that ruby glass was not produced locally, making a red find especially unusual there.",brown:"Amber, brown, clear, and olive shades fit Milwaukee's documented local glass-production history."}},
        michigan:{label:'Michigan Shoreline',refs:['Visit Southwest Michigan','Rock & Gem','Michigan Beachtowns'],blurb:"Michigan-side finds can reflect discarded bottles, jars, household and construction glass, shipping activity, and industrial material. Southwest Michigan sources describe white, brown, and light blue as especially familiar shoreline colors.",colorNote:{slag:"Michigan is the strongest regional match for industrial smelting slag such as Leland Blue and Frankfort Green; lake currents can also move slag away from its original source.",white:"Southwest Michigan sources describe white, brown, and light blue among the most commonly encountered beach-glass colors.",aqua:"Light blue and aqua are familiar finds in Southwest Michigan, often tied to older bottle and jar glass.",red:"Southwest Michigan sources describe red and orange as rare finds."}},
        unsure:{label:'General Lake Michigan',refs:['Rock & Gem','Michigan Beachtowns','Regional Michigan reporting'],blurb:"Without a precise shoreline, Lakeglass uses broad patterns only: discarded bottles, jars, household glass, construction material, and some ship-related debris can all contribute to beach glass. Color frequencies vary significantly from beach to beach.",colorNote:{}}
      };
      const THICKNESS_NOTES={thin:'Consistent with bottle-wall or thin tableware glass — the most common thickness on Great Lakes beaches.',medium:'Could be a jar base, plate edge, or thicker bottle heel — suggesting heavier packaging or tableware.',thick:'Worth a closer look — thick chunks can be bottle bases, insulators, or industrial slag.'};
      const MARK_NOTES={letters:'Raised lettering is one of the strongest clues; even a partial word or logo can sometimes identify a regional bottler.',ripple:'A rippled or wavy surface often points to older flat glass such as window or plate glass.',smooth:'Heavy, even frosting with softened edges generally suggests long tumbling and genuine age.',rough:'Remaining shine or sharper edges usually suggests less time in the water and a more recent break.'};
      window.LAKEGLASS_DATA={GLASS_COLORS,REGIONS,THICKNESS_NOTES,MARK_NOTES};
})();